BOARD_TAG    = micro
ARDUINO_LIBS = Adafruit_NeoPixel Control-Surface MIDIUSB SPI

# Workaround for MIDIUSB with 1.8.19: 1819 < 10606 (1.6.6)
ARDUINO_VERSION = 10819

CPPFLAGS = -DUSB_PRODUCT='"TouchPiano"'

include /usr/share/arduino/Arduino.mk
